name: Running Unit Test, Build Docker Image,  Push To Docker Hub and Deploy To EC2

on:
  pull_request:
    branches:
      - 'main'
  push: 
    branches:
      - 'main'

jobs:
  api-test:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
    - uses: actions/checkout@v2  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: running unitest
      run: go test ./... -cover -failfast
      
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: docker build golang
      run: |
        docker build . -t moryku/kampus_merdeka:1.0.0

    - name: docker push
      run: |
        docker push moryku/kampus_merdeka:1.0.0

    # - name: Build, Push and Release a Docker container to Heroku.
    #   uses: gonuit/heroku-docker-deploy@v1.3.3
    #   with: 
    #     email: ${{ secrets.HEROKU_EMAIL }}
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
    #     dockerfile_directory: ./
    #     dockerfile_name: Dockerfile
    #     docker_options: "--no-cache"
    #     process_type: web